# Generated by Django 3.2.16 on 2023-02-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('roll', models.CharField(max_length=150)),
                ('s_class', models.CharField(max_length=150)),
            ],
        ),
    ]
