# Generated by Django 3.2.16 on 2023-02-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='roll',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
