# Generated by Django 3.2.16 on 2023-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
