# Generated by Django 3.2.16 on 2023-03-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='ProfileImage/no_profile.png', upload_to='ProfileImage'),
        ),
    ]
